### PR TITLE
fix deprecated warnings

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nrinaudo** [comment]
Great, thanks for spotting this, I would never have realised it myself!

I'm seeing the same issue in:

* `CsvRowOps`
* `CsvSink`
* `CsvSource`

Happy to fix this myself, or to let you take this to its logical end if you want to, whichever is better for you.

**Comment by nevillelyh** [comment]
Addressed `CsvSink` & `CsvSource` as well. The one in `CsvRowOps` looks good to me.

**Comment by nrinaudo** [comment]
My fault, I meant CsvRowsOps. Again, this is busy work that I'm happy to do myself - the hard part was spotting the issue!

**Comment by nevillelyh** [comment]
No worries, just fixed.

**Comment by nrinaudo** [comment]
Looks good to me, thanks!

**Pull request merged**
